In [1]:
import math

1 .求解方程

In [14]:
def bisection(f, a, b):
    start = a 
    end = b
    
    # 求解二元一次方程
    if f(a)==0:
        return a
    elif f(b)==0:
        return b
    elif f(a)*f(b) > 0:
        print("无解")
        return
    else:
        # 二分查找方程的解
        mid = start + (end-start)/2.0
        while abs(mid - start) > 10**-7:
            if f(mid)==0:
                return mid
            elif f(a)*f(mid)<0:
                end = mid
            else:
                start=mid
            mid = start + (end-start)/2.0
        return mid
    
def f(x):
    return math.pow(x, 3) - 100*x + 3


In [15]:
bisection(f,1,500)

9.984966158983298

In [18]:
"""
Gaussian elimination method for solving a system of linear equations.
Gaussian elimination - https://en.wikipedia.org/wiki/Gaussian_elimination
"""


import numpy as np


def retroactive_resolution(coefficients: np.matrix, vector: np.array) -> np.array:
    """
    This function performs a retroactive linear system resolution
        for triangular matrix

    Examples:
        2x1 + 2x2 - 1x3 = 5         2x1 + 2x2 = -1
        0x1 - 2x2 - 1x3 = -7        0x1 - 2x2 = -1
        0x1 + 0x2 + 5x3 = 15
    >>> gaussian_elimination([[2, 2, -1], [0, -2, -1], [0, 0, 5]], [[5], [-7], [15]])
    array([[2.],
           [2.],
           [3.]])
    >>> gaussian_elimination([[2, 2], [0, -2]], [[-1], [-1]])
    array([[-1. ],
           [ 0.5]])
    """

    rows, columns = np.shape(coefficients)

    x = np.zeros((rows, 1), dtype=float)
    for row in reversed(range(rows)):
        sum = 0
        for col in range(row + 1, columns):
            sum += coefficients[row, col] * x[col]

        x[row, 0] = (vector[row] - sum) / coefficients[row, row]

    return x


def gaussian_elimination(coefficients: np.matrix, vector: np.array) -> np.array:
    """
    This function performs Gaussian elimination method

    Examples:
        1x1 - 4x2 - 2x3 = -2        1x1 + 2x2 = 5
        5x1 + 2x2 - 2x3 = -3        5x1 + 2x2 = 5
        1x1 - 1x2 + 0x3 = 4
    >>> gaussian_elimination([[1, -4, -2], [5, 2, -2], [1, -1, 0]], [[-2], [-3], [4]])
    array([[ 2.3 ],
           [-1.7 ],
           [ 5.55]])
    >>> gaussian_elimination([[1, 2], [5, 2]], [[5], [5]])
    array([[0. ],
           [2.5]])
    """
    # coefficients must to be a square matrix so we need to check first
    rows, columns = np.shape(coefficients)
    if rows != columns:
        return []

    # augmented matrix
    augmented_mat = np.concatenate((coefficients, vector), axis=1)
    augmented_mat = augmented_mat.astype("float64")

    # scale the matrix leaving it triangular
    for row in range(rows - 1):
        pivot = augmented_mat[row, row]
        for col in range(row + 1, columns):
            factor = augmented_mat[col, row] / pivot
            augmented_mat[col, :] -= factor * augmented_mat[row, :]

    x = retroactive_resolution(
        augmented_mat[:, 0:columns], augmented_mat[:, columns : columns + 1]
    )

    return x


if __name__ == "__main__":
#     import doctest

#     doctest.testmod()
    gaussian_elimination


2. 牛顿法求解方程的根

In [19]:
def newton(f, f_hat, start):
    """
    f:原函数
    f_hat:原函数的导数
    """
    x = start
    
    while True:
        x_ = x - f(x)/f_hat(x)
        if abs(x-x_) < 10**-5:
            return x_
        x = x_

def f(x):
    return (x**3) - (x**2) -3

def f_hat(x):
    return 3*x*x - 2*x

newton(f, f_hat, 3)

1.863706527819189

In [26]:
from decimal import Decimal
# 牛顿迭代法
def newton_raphson(func: str, a: int, precision: int = 10 ** -10) -> float:
    """ Finds root from the point 'a' onwards by Newton-Raphson method
    >>> newton_raphson("sin(x)", 2)
    3.1415926536808043
    >>> newton_raphson("x**2 - 5*x +2", 0.4)
    0.4384471871911695
    >>> newton_raphson("x**2 - 5", 0.1)
    2.23606797749979
    >>> newton_raphson("log(x)- 1", 2)
    2.718281828458938
    """
    x = a
    while True:
        x = Decimal(x) - (Decimal(eval(func)) / Decimal(eval(str(diff(func)))))
        # This number dictates the accuracy of the answer
        if abs(eval(func)) < precision:
            return float(x)
        
print(f"The root of sin(x) = 0 is {newton_raphson("x**2 - 5*x +2", 0.4)"})

SyntaxError: invalid syntax (<ipython-input-26-f216cea7c06c>, line 21)