# 4 TensorFlow的低阶API
张量结构操作诸如：张量创建，索引切片，维度变换，合并分割。
张量数学运算主要有：标量运算，向量运算，矩阵运算。另外我们会介绍张量运算的广播机制。

In [2]:
import tensorflow as tf

In [3]:
import numpy as np

## 1.创建张量

In [18]:
a = tf.constant([1,3,5], dtype = tf.float32)  # 一维常量
b = tf.range(1,10, delta=3)  # 一维常量，1-10，每次变化delta值
c = tf.linspace(0.0, 2*3.333, 100)  # 一维常量，0-2*3.33 的100个数
d = tf.zeros([2,3])   # 两行三列矩阵赋值为0

In [19]:
print(a,tf.rank(a),b,c,d, sep='\n')

tf.Tensor([1. 3. 5.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 4 7], shape=(3,), dtype=int32)
tf.Tensor(
[0.         0.06733333 0.13466667 0.20199999 0.26933333 0.33666667
 0.40399998 0.47133332 0.53866667 0.606      0.67333335 0.7406667
 0.80799997 0.8753333  0.94266665 1.01       1.0773333  1.1446667
 1.212      1.2793334  1.3466667  1.414      1.4813334  1.5486667
 1.6159999  1.6833333  1.7506666  1.818      1.8853333  1.9526666
 2.02       2.0873334  2.1546667  2.222      2.2893333  2.3566666
 2.424      2.4913332  2.5586667  2.626      2.6933334  2.7606666
 2.828      2.8953333  2.9626667  3.03       3.0973334  3.1646667
 3.2319999  3.2993333  3.3666666  3.434      3.5013332  3.5686667
 3.636      3.7033334  3.7706666  3.838      3.9053333  3.9726667
 4.04       4.107333   4.174667   4.242      4.3093333  4.3766665
 4.444      4.5113335  4.5786667  4.646      4.713333   4.780667
 4.848      4.9153333  4.9826665  5.05       5.1173334  5.1846666
 5

In [23]:
e = tf.ones([3,3,3]) # 三行三列三维张量赋值为1
f = tf.zeros_like(a,dtype= tf.float32)
g = tf.fill([3,2], 2)  # 用2填充三行两列的向量

In [24]:
print(e, b, g,sep='\n')

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 3, 3), dtype=float32)
tf.Tensor([1 4 7], shape=(3,), dtype=int32)
tf.Tensor(
[[2 2]
 [2 2]
 [2 2]], shape=(3, 2), dtype=int32)


In [29]:
# 均匀随机分布
tf.random.set_seed(1.0)
a = tf.random.uniform([5], minval=0, maxval=10)   # 
print(a)

tf.Tensor([1.6513085 9.014812  6.309742  4.345461  2.9193902], shape=(5,), dtype=float32)


In [32]:
# 正态随机分布
b = tf.random.normal([3,3], mean = 0.0, stddev=1.0)
tf.print(b)

[[-0.457012206 -0.406867266 0.728577793]
 [-0.892977774 0.312611461 0.994292498]
 [-1.7842623 -0.522005141 0.98080045]]


In [35]:
# 特殊矩阵
E = tf.eye(3,3)  # 单位矩阵
dig = tf.linalg.diag([1,2,3,4])   # 对角矩阵

In [36]:
tf.print(E, dig, sep='\n')

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 2.索引切片
张量的索引切片方式和numpy几乎是一样的。切片时支持缺省参数和省略号。对于tf.Variable,可以通过索引和切片对部分元素进行修改。
对于提取张量的连续子区域，也可以使用tf.slice.此外，对于不规则的切片提取,可以使用tf.gather,tf.gather_nd,tf.boolean_mask。
tf.boolean_mask功能最为强大，它可以实现tf.gather,tf.gather_nd的功能，并且tf.boolean_mask还可以实现布尔索引。
如果要通过修改张量的某些元素得到新的张量，可以使用tf.where，tf.scatter_nd。

In [55]:
tf.random.set_seed(3)
t = tf.random.uniform([4,3], minval=1, maxval = 10, dtype=tf.float32)
print(t)
tf.print(t[0])  #第0行
tf.print(t[-1]) #倒数第一行
print(t[0:3, :])
tf.print(t[1:4,:4:2])

tf.Tensor(
[[2.2029686 6.1106777 5.466985 ]
 [1.1517873 5.540876  7.738581 ]
 [2.1730318 4.0205345 6.8673496]
 [5.2853365 1.9348539 9.198882 ]], shape=(4, 3), dtype=float32)
[2.2029686 6.11067772 5.46698523]
[5.28533649 1.93485391 9.1988821]
tf.Tensor(
[[2.2029686 6.1106777 5.466985 ]
 [1.1517873 5.540876  7.738581 ]
 [2.1730318 4.0205345 6.8673496]], shape=(3, 3), dtype=float32)
[[1.15178728 7.73858118]
 [2.17303181 6.86734962]
 [5.28533649 9.1988821]]


In [56]:
# 索引和切片修改部分元素
x = tf.Variable([[1,2],[3,4]],dtype = tf.float32)
x[1,:].assign(tf.constant([0.0,0.0]))
tf.print(x)

[[1 2]
 [0 0]]


In [57]:
# 4个班，30个学生，9门课程
scores = tf.random.uniform((4,30,9),minval=0,maxval=100,dtype=tf.int32)
tf.print(scores)

[[[27 83 99 ... 79 6 97]
  [31 93 3 ... 63 31 50]
  [44 30 86 ... 57 59 85]
  ...
  [71 87 84 ... 79 57 62]
  [88 35 53 ... 89 94 4]
  [69 13 88 ... 48 9 45]]

 [[73 32 39 ... 74 51 37]
  [24 86 21 ... 76 6 11]
  [89 13 70 ... 4 78 40]
  ...
  [95 47 22 ... 60 2 45]
  [48 77 29 ... 98 50 28]
  [5 93 72 ... 48 59 13]]

 [[45 68 90 ... 30 71 92]
  [19 36 40 ... 23 97 57]
  [56 79 23 ... 24 52 42]
  ...
  [7 73 65 ... 91 68 24]
  [30 41 54 ... 13 10 52]
  [79 23 91 ... 63 65 79]]

 [[17 33 36 ... 81 97 93]
  [43 26 47 ... 8 35 33]
  [71 14 67 ... 46 50 4]
  ...
  [36 8 37 ... 38 85 24]
  [18 8 48 ... 89 99 59]
  [17 96 96 ... 40 64 97]]]


In [58]:
#抽取每个班级第0个学生，第5个学生，第9个学生的全部成绩
p = tf.gather(scores,[0,5,9],axis=1)
tf.print(p)

[[[27 83 99 ... 79 6 97]
  [20 96 97 ... 95 74 89]
  [37 15 28 ... 98 72 64]]

 [[73 32 39 ... 74 51 37]
  [69 24 32 ... 38 34 35]
  [52 29 4 ... 88 15 13]]

 [[45 68 90 ... 30 71 92]
  [95 6 34 ... 58 19 82]
  [2 2 72 ... 87 77 69]]

 [[17 33 36 ... 81 97 93]
  [28 91 7 ... 57 63 49]
  [11 76 54 ... 75 48 96]]]


In [62]:
#抽取每个班级第0个学生，第5个学生，第9个学生的第1门课程，第3门课程，第6门课程成绩
q = tf.gather(tf.gather(scores,[0,5,9],axis=1),[1],axis=2)
p = tf.gather(tf.gather(scores,[0,5,9],axis=1),[1,2],axis=2)
tf.print(q)
print(p)

[[[83]
  [96]
  [15]]

 [[32]
  [24]
  [29]]

 [[68]
  [6]
  [2]]

 [[33]
  [91]
  [76]]]
tf.Tensor(
[[[83 99]
  [96 97]
  [15 28]]

 [[32 39]
  [24 32]
  [29  4]]

 [[68 90]
  [ 6 34]
  [ 2 72]]

 [[33 36]
  [91  7]
  [76 54]]], shape=(4, 3, 2), dtype=int32)


In [63]:
# 抽取第0个班级第0个学生，第2个班级的第4个学生，第3个班级的第6个学生的全部成绩
#indices的长度为采样样本的个数，每个元素为采样位置的坐标
s = tf.gather_nd(scores,indices = [(0,0),(2,4),(3,6)])
s

<tf.Tensor: id=491, shape=(3, 9), dtype=int32, numpy=
array([[27, 83, 99,  9, 70, 67, 79,  6, 97],
       [57, 19, 83,  8, 34, 61, 10, 91, 11],
       [68, 80, 99, 62, 19, 33,  4, 45, 72]])>

###  修改张量
tf.where可以理解为if的张量版本，此外它还可以用于找到满足条件的所有元素的位置坐标。

tf.scatter_nd的作用和tf.gather_nd有些相反，tf.gather_nd用于收集张量的给定位置的元素，

而tf.scatter_nd可以将某些值插入到一个给定shape的全0的张量的指定位置处

In [66]:
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
d = tf.where(c<0, tf.fill(c.shape, np.nan), c)
print(c,d)

tf.Tensor(
[[-1.  1. -1.]
 [ 2.  2. -2.]
 [ 3. -3.  3.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[nan  1. nan]
 [ 2.  2. nan]
 [ 3. nan  3.]], shape=(3, 3), dtype=float32)


In [67]:
d = c - tf.scatter_nd([[0,0],[2,1]],[c[0,0],c[2,1]],c.shape)
d

<tf.Tensor: id=525, shape=(3, 3), dtype=float32, numpy=
array([[ 0.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3.,  0.,  3.]], dtype=float32)>

### 维度变换
维度变换相关函数主要有 tf.reshape, tf.squeeze, tf.expand_dims, tf.transpose.

tf.reshape 可以改变张量的形状。

tf.squeeze 可以减少维度。

tf.expand_dims 可以增加维度。

tf.transpose 可以交换维度。

In [74]:
z = tf.random.uniform(shape=[1,3,3,2], minval=0,maxval=255,dtype=tf.int32)
print(z)
b = tf.reshape(z, [3,6])
tf.print(b)

tf.Tensor(
[[[[200 180]
   [172 250]
   [ 40 212]]

  [[133 222]
   [157 225]
   [110  48]]

  [[233 126]
   [251  60]
   [186   8]]]], shape=(1, 3, 3, 2), dtype=int32)
[[200 180 172 250 40 212]
 [133 222 157 225 110 48]
 [233 126 251 60 186 8]]


In [75]:
s = tf.squeeze(z)  # 消除一个维度
s

<tf.Tensor: id=566, shape=(3, 3, 2), dtype=int32, numpy=
array([[[200, 180],
        [172, 250],
        [ 40, 212]],

       [[133, 222],
        [157, 225],
        [110,  48]],

       [[233, 126],
        [251,  60],
        [186,   8]]])>

In [76]:
d = tf.expand_dims(s,axis=0) #在第0维插入长度为1的一个维度
d

<tf.Tensor: id=569, shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[200, 180],
         [172, 250],
         [ 40, 212]],

        [[133, 222],
         [157, 225],
         [110,  48]],

        [[233, 126],
         [251,  60],
         [186,   8]]]])>

In [77]:
# Batch,Height,Width,Channel
a = tf.random.uniform(shape=[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

# 转换成 Channel,Height,Width,Batch
s= tf.transpose(a,perm=[3,1,2,0])
tf.print(s.shape)

TensorShape([100, 600, 600, 4])
TensorShape([4, 600, 600, 100])


### 合并分割

In [78]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.concat([a,b,c],axis = 0)  # 连接向量

<tf.Tensor: id=583, shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [79]:
tf.concat([a,b,c],axis = 1)

<tf.Tensor: id=586, shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  5.,  6.,  9., 10.],
       [ 3.,  4.,  7.,  8., 11., 12.]], dtype=float32)>

In [80]:
tf.stack([a,b,c])  # 张量堆叠

<tf.Tensor: id=588, shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>